#! /bin/bash 
# baut PDF aus .tex, schreibt Fehler in stdout und in buildErrors
# tritt ein Fehler auf wird buildErrors geöffnet
# außerdem wird die entstandene pdf eine Verzeichnisebene nach oben geschoben 
# TODO und FIXME Kommentare werden rausgezogen und in eine Datei gespeichert

pdflatex -file-line-error -interaction nonstopmode $@ | grep $1':[0-9]*\|File ended while\|LaTeX Warning\|no line here to end\|specifier changed\|Undefined' | tee buildErrors

cp $(echo $1 | sed s/tex/pdf/g) ../
if [[ -s buildErrors ]] 
then
	less buildErrors

fi

grep -nR --include '*.tex' 'TODO\|FIXME' | sed -r s/%/\\n\\t/g | tee ../TODO

# create backup folder in case there are backup filesa

if ls *backup 1> /dev/null 2>&1
then
	[ -d Backup ] || mkdir Backup
	mv *.backup ./Backup
fi

echo "done"
